aceh_urls = {
    "/wiki/Rencong",
    "/wiki/Tari_Saman",
    "/wiki/Didong",
    "/wiki/Kerawang_Gayo",
    "/wiki/Tari_Seudati",
    "/wiki/Rumah_adat_Aceh",
    "/wiki/Kopiah_Riman",
    "/wiki/Tari_Rapa%27i_Geleng",
    "/wiki/Tari_Dampeng",
    "/wiki/Tari_Bines",
    "/wiki/Pinto_Aceh",
    "/wiki/Tari_Rabbani_Wahid",
    "/wiki/Mak_Meugang",
    "/wiki/Nandong",
    "/wiki/Guel",
    "/wiki/Tari_Likok_Pulo",
    "/wiki/Pacu_Kude",
    "/wiki/Menatakhken_Hinei",
    "/wiki/Canang_Kayu",
    "/wiki/Maracu",
    "/wiki/Landok_Sampot",
    "/wiki/Rapai_Pase",
    "/wiki/Payung_Mesikhat",
    "/wiki/Pasenatken",
    "/wiki/Rapa%27i_Geurimpheng",
    "/wiki/Keumamah",
    "/wiki/Laweut",
    "/wiki/Likee",
    "/wiki/Panglima_Laot",
    "/wiki/Kuah_Beulangong",
    "/wiki/Keni_Gayo",
    "/wiki/Pemamanan",
    "/wiki/Memek_(makanan)",
    "/wiki/Gutel",
    "/wiki/Sining",
    "/wiki/Silat_Pelintau",
    "/wiki/Peusijuek",
    "/wiki/Keuneunong",
    "/wiki/Tari_Rapa%27i_Bubee",
    "/wiki/Kupiah_meukeutob",
    "/wiki/Sie_Reuboh",
    "/wiki/Tangis_Dilo",
    "/wiki/Bahasa_Devayan"
}

sumatera_utara_urls = {
    "/wiki/Tor-Tor",
    "/wiki/Gordang_Sambilan",
    "/wiki/Siwaluh_Jabu",
    "/wiki/Huda-huda",
    "/wiki/Omo_Hada",
    "/wiki/Bola_Nafo",
    "/wiki/Tari_Serampang_12",
    "/wiki/Berahoi",
    "/wiki/Merdang-Merdem",
    "/wiki/Ulos_Batak_Toba",
    "/wiki/Pustaha_Lak-Lak",
    "/wiki/Erpangir_Ku_Lau",
    "/wiki/Parmalim",
    "/wiki/Ni_%27Oworu",
    "/wiki/Dayok_Binatur",
    "/wiki/Genderang_sisibah",
    "/wiki/Holat",
    "/wiki/Toge_Panyabungan",
    "/wiki/Tari_Gubang",
    "/wiki/Babae",
    "/wiki/Tari_dulang",
    "/wiki/Sinandong_asahan",
    "/wiki/Gendang_guro-guro_aron",
    "/wiki/Pelleng",
    "/wiki/Gotong",
    "/wiki/Itak_Poul_Poul",
    "/wiki/Kala_Bubu",
    "/wiki/Mangarontas",
    "/wiki/Tari_Tortor_Sombah",
    "/wiki/Maena",
    "/wiki/Hombo_Batu",
    "/wiki/Tari_Moyo",
    "/wiki/Hoho"
}

sumatera_barat_urls = {
    "/wiki/Randang",
    "/wiki/Rumah_Gadang",
    "/wiki/Sistem_Garis_Keturunan_Ibu_di_Masyarakat_Minangkabau",
    "/wiki/Kaba_Cindua_Mato",
    "/wiki/Tari_Toga",
    "/wiki/Songket_Pandai_Sikek",
    "/wiki/Rongeng_Pasaman",
    "/wiki/Indang_Piaman",
    "/wiki/Tato_Mentawai",
    "/wiki/Silek_Minang",
    "/wiki/Ulu_Ambek",
    "/wiki/Rabab",
    "/wiki/Salawat_Dulang",
    "/wiki/Pasambahan",
    "/wiki/Batombe",
    "/wiki/Tari_Tanduak",
    "/wiki/Tari_Piriang_(Tari_Piring)",
    "/wiki/Randai",
    "/wiki/Bahasa_Tansi_Sawahlunto",
    "/wiki/Babiola",
    "/wiki/Talempong_Unggan",
    "/wiki/Tari_Benten",
    "/wiki/Sikerei",
    "/wiki/Botatah",
    "/wiki/Arak_Bako",
    "/wiki/Songket_Silungkang",
    "/wiki/Sikambang_Manih",
    "/wiki/Tari_kain",
    "/wiki/Anak_Balam",
    "/wiki/Diki_Pano",
    "/wiki/Balimau",
    "/wiki/Badampiang",
    "/wiki/Basapa",
    "/wiki/Marosok",
    "/wiki/Uma",
    "/wiki/Tari_Balanse_Madam",
    "/wiki/Pacu_Jawi",
    "/wiki/Pacu_itiak",
    "/wiki/Gamad",
    "/wiki/Randang_paku",
    "/wiki/Bansi",
    "/wiki/Tambua_Tasa",
    "/wiki/Saluang",
    "/wiki/Dadih",
    "/wiki/Makan_bajamba",
    "/wiki/Batik_Tanah_Liat",
    "/wiki/Malamang",
    "/wiki/Teh_talua",
    "/wiki/Aia_kawa",
    "/wiki/Sijobang",
    "/wiki/Rumah_Gadang_Kajang_Padati",
    "/wiki/Badoncek",
    "/wiki/Serak_Gulo"
}

riau_place_urls = {
    "/wiki/Tenun_Siak",
    "/wiki/Koba",
    "/wiki/Pacu_Jalur",
    "/wiki/Menumbai_Pelalawan",
    "/wiki/Randai_Kuantan",
    "/wiki/Nyanyi_Panjang",
    "/wiki/Bedewo_Bonai",
    "/wiki/Debus_Indragiri_Hulu",
    "/wiki/Calempong_Oguong",
    "/wiki/Joget_Sonde",
    "/wiki/Tunjuk_Ajar_Melayu",
    "/wiki/Sijobang",
    "/wiki/Silat_perisai",
    "/wiki/Zapin_Api",
    "/wiki/Zapin_Meskom",
    "/wiki/Manongkah",
    "/wiki/Perahu_Beganduang",
    "/wiki/Batobo",
    "/wiki/Rumah_Lontiok",
    "/wiki/Selembayung_Riau",
    "/wiki/Onduo_Rokan",
    "/wiki/Silek_Tigo_Bulan",
    "/wiki/Syair_Siak_Sri_Indrapura",
    "/wiki/Ratik_Bosa/_Ratik_Tagak",
    "/wiki/Ghatib_Beghanyut",
    "/wiki/Lukah_Gilo_Riau",
    "/wiki/Belian_Riau",
    "/wiki/Silat_Pangean",
    "/wiki/Kotik_Adat_Kampar",
    "/wiki/Badondong",
    "/wiki/Nandung_Indragiri_Hulu",
    "/wiki/Kayat_Kuansing/Kayat_Rantau_Kuantan",
    "/wiki/Pantun_Atui",
    "/wiki/Tari_Gendong",
    "/wiki/Burung_Kwayang",
    "/wiki/Tari_Cegak",
    "/wiki/Tari_Zapin",
    "/wiki/Syair_Surat_Kapal",
    "/wiki/Tepuk_tepung_tawar",
    "/wiki/Dikei_Sakai",
    "/wiki/Tari_Inai_Piring_Dua_Belas",
    "/wiki/Upah-upah"
}

kepulauan_riau_urls = {
    "/wiki/Makyong",
    "/wiki/Gurindam_Dua_Belas",
    "/wiki/Gazal",
    "/wiki/Pantun_Melayu",
    "/wiki/Gendang_Siantan",
    "/wiki/Tari_Gubang",
    "/wiki/Teater_Bangsawan",
    "/wiki/Joget_Dangkong",
    "/wiki/Bejenjang",
    "/wiki/Tari_Inai",
    "/wiki/Tepuk_Tepung_Tawar_Kepulauan_Riau",
    "/wiki/Bubur_Lambok_Lingga",
    "/wiki/Mandi_Syafar_Kepulauan_Riau",
    "/wiki/Ratib_Saman_Lingga",
    "/wiki/Silat_Pengantin_Kepulauan_Riau",
    "/wiki/Basuh_Lantai",
    "/wiki/Bersih_Tembuni_Lingga",
    "/wiki/Bela_Kampong",
    "/wiki/Kue_bangkit",
    "/wiki/Kue_batang_buruk"
}

jambi_urls = {
    "/wiki/Krinok",
    "/wiki/Aksara_Kaganga",
    "/wiki/Aksara_Incung",
    "/wiki/Seloko_Melayu_Jambi",
    "/wiki/Hadrah",
    "/wiki/Besale",
    "/wiki/Upacara_Asyeik",
    "/wiki/Tauh_(Betauh)",
    "/wiki/Tari_Kain_Kromong",
    "/wiki/Musik_Kalinong",
    "/wiki/Tari_elang",
    "/wiki/Tomboi_Sialong",
    "/wiki/Tomboi_Ngambek_Rapa",
    "/wiki/Sebelik_Sumpah",
    "/wiki/Ambung_Orang_Rimbo",
    "/wiki/Cawot",
    "/wiki/Ubat_Ramuon_Orang_Rimbo",
    "/wiki/Belangun_Orang_Rimbo",
    "/wiki/Hompongon",
    "/wiki/Musik_Gambang_Dano_Lamo",
    "/wiki/Tari_kadam",
    "/wiki/Rangguk_Kumun",
    "/wiki/Lapaek_Koto_Dian_Rawang",
    "/wiki/Kenduri_Sko",
    "/wiki/Tauh_Lempur",
    "/wiki/Ntak_Awo",
    "/wiki/Ampek_Gonjie_Limo_Gonop",
    "/wiki/Perkampungan_Tradisional_Rumah_Tuo_Rantau_Panjang",
    "/wiki/Tari_Iyo-Iyo",
    "/wiki/Ngagoah_Imo_Pulau_Tengah",
    "/wiki/Tari_Ayam_Biring",
    "/wiki/Dadung"
}

sumatera_selatan_urls = {
    "/wiki/Dulmuluk",
    "/wiki/Songket_Palembang",
    "/wiki/Tari_Gending_Sriwijaya",
    "/wiki/Tembang_Batanghari_Sembilan",
    "/wiki/Pempek",
    "/wiki/Rumah_Ulu",
    "/wiki/Limas_Palembang",
    "/wiki/Senjang",
    "/wiki/Rumah_Besemah",
    "/wiki/Lak",
    "/wiki/Tari_penguton",
    "/wiki/Adat_Timbang_Kepala_Kebo",
    "/wiki/Ngobeng",
    "/wiki/Tari_Kebagh",
    "/wiki/Tari_Silampari_Kahyangan_Tinggi",
    "/wiki/Pindang_Palembang",
    "/wiki/Tikar_Purun_Pedamaran",
    "/wiki/Surat_Ulu",
    "/wiki/Midang",
    "/wiki/Tanjak_Palembang",
    "/wiki/Cak_Ingkling",
    "/wiki/Sedekah_Serabi",
    "/wiki/Sedekah_Rame",
    "/wiki/Sagarurung",
    "/wiki/Burgo"
}

lampung_urls = {
    "/wiki/Tapis",
    "/wiki/Tari_Melinting",
    "/wiki/Gamolan_pekhing",
    "/wiki/Tari_Sigeh_Penguten",
    "/wiki/Gulai_Taboh",
    "/wiki/Seruit",
    "/wiki/Cakak_Pepadun",
    "/wiki/Warahan_Lampung",
    "/wiki/Kakiceran",
    "/wiki/Maduaro",
    "/wiki/Tari_Nyambai",
    "/wiki/Bediom",
    "/wiki/Tari_Bedayou_Tulang_Bawang",
    "/wiki/Dadi",
    "/wiki/Siger_Lampung",
    "/wiki/Ketaro_Adat_Lappung",
    "/wiki/Nyuncun_Pahakh",
    "/wiki/Tari_Bedana_Lampung",
    "/wiki/Sebambangan",
    "/wiki/Nyubuk_Majeu",
    "/wiki/Kias",
    "/wiki/Tari_Kiamat",
    "/wiki/Piil_Pesenggiri",
    "/wiki/Badik_Lampung",
    "/wiki/Mekhatin",
    "/wiki/Adok",
    "/wiki/Hahiwang"
}

bengkulu_urls = {
    "/wiki/Kain_Besurek",
    "/wiki/Kain_Lantung",
    "/wiki/Uemak_Potong_Jang",
    "/wiki/Bekejai_(Upacara_Perkawinan_Suku_Rejang)",
    "/wiki/Tari_Kejai",
    "/wiki/Tari_Gandai",
    "/wiki/Guritan_Kaur_Bengkulu",
    "/wiki/Ringit",
    "/wiki/Serunai_Bengkulu",
    "/wiki/Tadutan",
    "/wiki/Melemang",
    "/wiki/Dhol"
}

bangka_belitung_urls = {
    "/wiki/Muang_Jong",
    "/wiki/Perang_Ketupat",
    "/wiki/Adu_Kerito_Surong",
    "/wiki/Kain_Cual",
    "/wiki/Upacara_Adat_Nujuh_Jerami",
    "/wiki/Maras_Taun",
    "/wiki/Sepen_penyok",
    "/wiki/Pakaian_Pengantin_Paksian",
    "/wiki/Gangan",
    "/wiki/Antu_Bubu",
    "/wiki/Serimbang",
    "/wiki/Hadrah_Gendang_Empat_Belitong",
    "/wiki/Emping_Beras",
    "/wiki/Sepen_Buding"
}

gorontalo_urls = {
    "/wiki/Molapi_saronde",
    "/wiki/Tumbilotohe",
    "/wiki/Karawo",
    "/wiki/Polopalo",
    "/wiki/Tanggomo",
    "/wiki/Lohidu",
    "/wiki/Langga",
    "/wiki/Binte_Biluhuta",
    "/wiki/Paiya_Lohungo_Lopoli",
    "/wiki/Tuja%27i",
    "/wiki/Wunungo",
    "/wiki/Tidi_lo_Polopalo",
    "/wiki/Palebohu",
    "/wiki/Dikili",
    "/wiki/Me%27eraji",
    "/wiki/Pulanga",
    "/wiki/Momeati",
    "/wiki/Molalunga",
    "/wiki/Momuhuto",
    "/wiki/Tolobalango",
    "/wiki/Bantayo_Poboide",
    "/wiki/Upiya_Karanji",
    "/wiki/Molontalo",
    "/wiki/Ilabulo",
    "/wiki/Leningo",
    "/wiki/Bili%27u",
    "/wiki/Wunungo",
    "/wiki/Paluwala",
    "/wiki/Wolimomo"
}

dki_jakarta_urls = {
    "/wiki/Ondel-ondel",
    "/wiki/Lenong",
    "/wiki/Upacara_Babarit",
    "/wiki/Nasi_Uduk",
    "/wiki/Sayur_Besan",
    "/wiki/Kerak_Telor",
    "/wiki/Gabus_Pucung",
    "/wiki/Roti_Buaya",
    "/wiki/Bir_Pletok",
    "/wiki/Tanjidor",
    "/wiki/(Buka)_Palang_Pintu",
    "/wiki/Gambang_Kromong",
    "/wiki/Silat_Beksi",
    "/wiki/Samrah",
    "/wiki/Keroncong_Tugu",
    "/wiki/Topeng_Blantek",
    "/wiki/Soto_Betawi",
    "/wiki/Gado-gado_Betawi",
    "/wiki/Rias_Besar",
    "/wiki/Kebaya_Kerancang",
    "/wiki/Batik_Betawi",
    "/wiki/Topeng_tunggal",
    "/wiki/Penganten_Sunat",
    "/wiki/Rebana_Biang",
    "/wiki/Hadroh_Betawi",
    "/wiki/Dodol_Betawi",
    "/wiki/Silat_Cingkrik",
    "/wiki/Bahasa_Betawi",
    "/wiki/Caca_Gulali",
    "/wiki/Cici_Putri",
    "/wiki/Kembang_Kelape",
    "/wiki/Uncul",
    "/wiki/Nasi_Ulam_Betawi",
    "/wiki/Wayang_Kulit_Betawi",
    "/wiki/Silat_Mustika_Kwitang",
    "/wiki/Ketupat_Sayur_Babanci",
    "/wiki/Kue_Sengkulun",
    "/wiki/Selendang_Mayang",
    "/wiki/Silat_Sabeni_Tenabang",
    "/wiki/Asinan_Betawi",
    "/wiki/Dangdut"
}

jawa_barat_urls = {
    "/wiki/Kujang",
    "/wiki/Ronggeng_Gunung",
    "/wiki/Sisingaan",
    "/wiki/Angklung",
    "/wiki/Tari_Topeng_Cirebon",
    "/wiki/Kuda_Renggong",
    "/wiki/Jaipong",
    "/wiki/Sintren",
    "/wiki/Ngarot",
    "/wiki/Ngalungsur_Geni_(Ngalungsur_Pusaka)",
    "/wiki/Lais_Garut",
    "/wiki/Lukis_kaca_Cirebon",
    "/wiki/Gembyung",
    "/wiki/Iket_Sunda",
    "/wiki/Kolecer_Jawa_Barat",
    "/wiki/Leuit",
    "/wiki/Nyangku",
    "/wiki/Angklung_Buncis",
    "/wiki/Badud",
    "/wiki/Bebegig",
    "/wiki/Gaok",
    "/wiki/Gondang_Buhun",
    "/wiki/Hajat_Laut",
    "/wiki/Kuda_Kosong",
    "/wiki/Ngabungbang_Batulawang",
    "/wiki/Ngalaksa",
    "/wiki/Reog_Dongkol",
    "/wiki/Sate_Maranggi",
    "/wiki/Tarawangsa",
    "/wiki/Tari_Kedempling",
    "/wiki/Tari_Umbul",
    "/wiki/Tarling",
    "/wiki/Uyeg",
    "/wiki/Badawang",
    "/wiki/Benjang_(beladiri)",
    "/wiki/Cingcowong",
    "/wiki/Domyak",
    "/wiki/Kawin_Cai",
    "/wiki/Upacara_panjang_jimat",
    "/wiki/Tari_Randu_Kentir",
    "/wiki/Topeng_Banjet",
    "/wiki/Tari_Merak",
    "/wiki/Angklung_Bungko",
    "/wiki/Gong_Si_Bolong",
    "/wiki/Toleat",
    "/wiki/Payung_geulis",
    "/wiki/Jipeng",
    "/wiki/Karinding",
    "/wiki/Doclang",
    "/wiki/Degung",
    "/wiki/Gong_Renteng_Cirebon",
    "/wiki/Tari_Ketuk_Tilu",
    "/wiki/Bedaya_Rimbe",
    "/wiki/Celempung",
    "/wiki/Kiliningan",
    "/wiki/Longser",
    "/wiki/Arumba",
    "/wiki/Krupuk_Mlarat",
    "/wiki/Sega_Jamblang",
    "/wiki/Wajit"
}

banten_urls = {
    "/wiki/Debus_Banten",
    "/wiki/Tari_Cokek",
    "/wiki/Sate_bandeng",
    "/wiki/Seren_taun",
    "/wiki/Golok_Sulangkar",
    "/wiki/Golok_Ciomas",
    "/wiki/Zikir_Saman",
    "/wiki/Patingtung",
    "/wiki/Wayang_Garing",
    "/wiki/Tari_Rudat_Banten",
    "/wiki/Koja",
    "/wiki/Maca_Syekh",
    "/wiki/Gambang_Kromong"
}

jawa_tengah_urls = {
    "/wiki/Keris",
    "/wiki/Lumpia_Semarang",
    "/wiki/Ukir_Jepara",
    "/wiki/Upacara_Adat_Apeman_Yaqowiyu",
    "/wiki/Ruwatan_Rambut_Gimbal",
    "/wiki/Meron",
    "/wiki/Tari_Gambyong",
    "/wiki/Joglo_Pencu_(Rumah_Adat_Kudus)",
    "/wiki/Tempe_Jawa_Tengah",
    "/wiki/Barongan_Blora",
    "/wiki/Gethuk_Goreng_Sokaraja",
    "/wiki/Manten_Kaji",
    "/wiki/Tari_Endel",
    "/wiki/Grebeg_Besar_Demak",
    "/wiki/Hak-Hakan",
    "/wiki/Gambang_Semarang",
    "/wiki/Begalan_Banyumas",
    "/wiki/Kethek_Ogleng_Wonogiri",
    "/wiki/Sedulur_Sikep_Blora",
    "/wiki/Dolalak",
    "/wiki/Sintren",
    "/wiki/Jamu",
    "/wiki/Dakon_Jawa_Tengah",
    "/wiki/Dugderan",
    "/wiki/Wayang_suket",
    "/wiki/Perang_Obor_Tegalsambi",
    "/wiki/Jembul_Tulakan",
    "/wiki/Telur_Asin_Brebes",
    "/wiki/Pesta_Lomban",
    "/wiki/Tari_Topeng_Lengger",
    "/wiki/Bundengan",
    "/wiki/Sate_Kere",
    "/wiki/Seni_pertunjukan",
    "/wiki/Sate_Buntel",
    "/wiki/Ngesti_Pandowo",
    "/wiki/Warak_ngendog",
    "/wiki/Barongan_Kudus",
    "/wiki/Jenang_Kudus",
    "/wiki/Tempe_kemul",
    "/wiki/Batik_Salem",
    "/wiki/Potehi"
}

yogyakarta_urls = {
    "/wiki/Joglo",
    "/wiki/Gudeg",
    "/wiki/Saparan",
    "/wiki/Labuhan_Alit_Keraton_Yogyakarta",
    "/wiki/Tari_Angguk",
    "/wiki/Badui",
    "/wiki/Khuntulan",
    "/wiki/Montro",
    "/wiki/Rinding_Gumbeng",
    "/wiki/Srandul",
    "/wiki/Panjidur",
    "/wiki/Tari_Golek_Menak",
    "/wiki/Srimpi_Ronggo_Janur",
    "/wiki/Dadung_Awuk",
    "/wiki/Krumpyung_Kulon_Progo",
    "/wiki/Wedang_uwuh",
    "/wiki/Wayang_Beber_Remeng_Mangunjoyo",
    "/wiki/Wayang_wong_gaya_yogyakarta",
    "/wiki/Wayang_Kancil_Yogyakarta",
    "/wiki/Beksan_Jebeng",
    "/wiki/Beksan_Floret",
    "/wiki/Bedhaya_Tejanata_Pakualaman",
    "/wiki/Bedhaya_Kuwung-Kuwung",
    "/wiki/Beksan_Guntur_Segara",
    "/wiki/Beksan_Bugis_Gaya_Yogyakarta",
    "/wiki/Kethek_ogleng",
    "/wiki/Gejog_Lesung_Yogyakarta",
    "/wiki/Macapatan_Yogyakarta",
    "/wiki/Benthik_Yogyakarta",
    "/wiki/Peksi_Moi",
    "/wiki/Saparan_Wonolelo",
    "/wiki/Rabu_pungkasan",
    "/wiki/Geplak",
    "/wiki/Geblek",
    "/wiki/Dandan_Kali",
    "/wiki/Tayub_Yogyakarta",
    "/wiki/Brongkos_Yogyakarta",
    "/wiki/Beksan_Etheng",
    "/wiki/Golek_Lambangsari_Yogyakarta",
    "/wiki/Batik_Nitik_Yogyakarta",
    "/wiki/Beksan_Golek_Pucung_Kethoprak",
    "/wiki/Nini_Thowong_Yogyakarta",
    "/wiki/Sate_klatak",
    "/wiki/Mi_letheg",
    "/wiki/Kipo",
    "/wiki/Growol",
    "/wiki/Kampung_Pitu",
    "/wiki/Nguras_Enceh",
    "/wiki/Besengek",
    "/wiki/Rasulan",
    "/wiki/Reog_Wayang",
    "/wiki/Upacara_adat_Mbah_Bregas",
    "/wiki/Tuk_si_bedug",
    "/wiki/Jemparingan",
    "/wiki/Thiwul",
    "/wiki/Lemper",
    "/wiki/Gudeg_Manggar",
    "/wiki/Gobak_sodor",
    "/wiki/Sayur_lodeh",
    "/wiki/Jadah_manten",
    "/wiki/Jamu",
    "/wiki/Yangko",
    "/wiki/Aksara_Jawa"
}

jawa_timur_urls = {
    "/wiki/Reog_Ponorogo",
    "/wiki/Keraben_Sape_(Karapan_Sapi)",
    "/wiki/Sapi_Sonok",
    "/wiki/Gandrung_Banyuwangi",
    "/wiki/Kentrung",
    "/wiki/Tari_Seblang",
    "/wiki/Wayang_Topeng",
    "/wiki/Tumpeng_Sewu",
    "/wiki/Syiir_Madura",
    "/wiki/Kasada",
    "/wiki/Ludruk",
    "/wiki/Jaran_Bodhag",
    "/wiki/Dongkrek",
    "/wiki/Larung_Sembonyo",
    "/wiki/Singo_Ulung",
    "/wiki/Wayang_Beber",
    "/wiki/Tanean_lanjang",
    "/wiki/Jaran_Kencak",
    "/wiki/Wayang_krucil",
    "/wiki/Ayam_lodho",
    "/wiki/Sandhur_Manduro",
    "/wiki/Nyadar_(upacara_adat)",
    "/wiki/Ceprotan",
    "/wiki/Jamasan_Gong_Kiai_Pradah",
    "/wiki/Damar_Kurung",
    "/wiki/Celurit",
    "/wiki/Janger_Banyuwangi",
    "/wiki/Manten_kucing",
    "/wiki/Rawon_Nguling_Probolinggo",
    "/wiki/Reog_Cemandi",
    "/wiki/Sandur",
    "/wiki/Wayang_Thengul",
    "/wiki/Topeng_jatiduwur",
    "/wiki/Bantengan",
    "/wiki/Ojhung",
    "/wiki/Saronen",
    "/wiki/Tetaken",
    "/wiki/Rujak_cingur",
    "/wiki/Nasi_krawu",
    "/wiki/Wayang_krucil",
    "/wiki/Pecel_Madiun",
    "/wiki/Jaranan_Pegon",
    "/wiki/Jaran_Jenggo",
    "/wiki/Tari_Ngremo",
    "/wiki/Brem"
}

bali_urls = {
    "/wiki/Mekepung",
    "/wiki/Kain_gringsing",
    "/wiki/Endek",
    "/wiki/Barong_Bali#Barong_Ket_atau_Barong_Keket",
    "/wiki/Joged",
    "/wiki/Legong",
    "/wiki/Wayang_orang",
    "/wiki/Gambuh",
    "/wiki/Topeng_Sidakarya",
    "/wiki/Tari_Sanghyang",
    "/wiki/Tari_Rejang",
    "/wiki/Mekotek",
    "/wiki/Ter-teran",
    "/wiki/Gebug_ende",
    "/wiki/Ayam_betutu",
    "/wiki/Gamelan_Selonding",
    "/wiki/Usaba_Dangsil",
    "/wiki/Usaba_Sumbu",
    "/wiki/Siat_tipat_bantal",
    "/wiki/Leko",
    "/wiki/Siat_Geni",
    "/wiki/Jegog",
    "/wiki/Terompong_beru",
    "/wiki/Megibung",
    "/wiki/Mesabat-Sabatan_Biu",
    "/wiki/Songket_Beratan",
    "/wiki/Tari_baris_wayang",
    "/wiki/Tari_baris_cina",
    "/wiki/Basmerah",
    "/wiki/Ngarebong_Kesiman",
    "/wiki/Tari_Taruna_Jaya",
    "/wiki/Nyakan_Diwang",
    "/wiki/Sate_Renteng",
    "/wiki/Mandolin",
    "/wiki/Babi_guling",
    "/wiki/Sate_Lilit",
    "/wiki/Ngaben",
    "/wiki/Melukat",
    "/wiki/Nyepi"
}

nusa_tenggara_barat_urls = {
    "/wiki/Gendang_Beleq",
    "/wiki/Perisean",
    "/wiki/Ayam_Taliwang",
    "/wiki/Pacoa_Jara,_Pacu_Mbojo",
    "/wiki/Kareku_Kandei",
    "/wiki/Bau_Nyale",
    "/wiki/Tenun_Pringgasela"
}

nusa_tenggara_timur_urls = {
    "/wiki/Sasandu_(Sasando)",
    "/wiki/Caci",
    "/wiki/Rumah_Bale_(Arsitektur_Sumba)",
    "/wiki/Tenun_Ikat_Sumba",
    "/wiki/Lodok",
    "/wiki/Penti_Weki_Peso_Beo_Reca_Rangga_Wali_Ntaung",
    "/wiki/Mbaru_Niang_Wae_Rebo",
    "/wiki/Pasola",
    "/wiki/Etu",
    "/wiki/Repit",
    "/wiki/Kure",
    "/wiki/Wulla_Poddu",
    "/wiki/Leru_Weru",
    "/wiki/Matekio",
    "/wiki/Tari_Likurai",
    "/wiki/Se%27i",
    "/wiki/Leva_nuang",
    "/wiki/Ela_Ma",
    "/wiki/Hole_(adat_istiadat)",
    "/wiki/Vera",
    "/wiki/Ti%27i_langga",
    "/wiki/Ja%27i"
}

kalimantan_barat_urls = {
    "/wiki/Festival_meriam_karbit",
    "/wiki/Robo-robo",
    "/wiki/Nyangahatn",
    "/wiki/Jonggan",
    "/wiki/Sape_Kalimantan_Barat",
    "/wiki/Tumpang_Negeri",
    "/wiki/Gawai_Dayak_Kalimantan_Barat",
    "/wiki/Tenun_Corak_Insang",
    "/wiki/Panganten_Dayak_Kanayatn",
    "/wiki/Faradje%27",
    "/wiki/Sayo%27_Keladi_Pontianak",
    "/wiki/Pacri_Nenas_Pontianak",
    "/wiki/Temet",
    "/wiki/Bahasa_Melayu_Pontianak",
    "/wiki/Bahasa_Melayu_Sambas"
}

kalimantan_selatan_urls = {
    "/wiki/Sasirangan",
    "/wiki/Madihin",
    "/wiki/Aruh_Baharin",
    "/wiki/Pasar_Terapung",
    "/wiki/Lamut",
    "/wiki/Kuriding/_Guriding",
    "/wiki/Bubungan_Tinggi",
    "/wiki/Ba%27ayun_Mulud/Maulid",
    "/wiki/Batatamba",
    "/wiki/Mamanda",
    "/wiki/Tari_Baksa_Kembang",
    "/wiki/Wayang_Kulit_Banjar",
    "/wiki/Air_Guci",
    "/wiki/Kuda_gipang",
    "/wiki/Sinoman_Hadrah",
    "/wiki/Wayang_Gung",
    "/wiki/Balogo",
    "/wiki/Mappanretasi_Pagatan",
    "/wiki/Tenun_Pagatan",
    "/wiki/Damarulan/Damarwulan_Banjarmasin",
    "/wiki/Nasi_Astakona",
    "/wiki/Rumah_Lanting",
    "/wiki/Kurung-kurung",
    "/wiki/Aruh_Bawanang",
    "/wiki/Batatamba",
    "/wiki/Tari_Banjar",
    "/wiki/Tari_Radap_Rahayu",
    "/wiki/Ladon",
    "/wiki/Mesiwah_Pare_Gumboh",
    "/wiki/Bapandung",
    "/wiki/Arangan"
}

kalimantan_tengah_urls = {
    "/wiki/Tiwah",
    "/wiki/Sapundu",
    "/wiki/Mamapus_Lewu",
    "/wiki/Nahunan",
    "/wiki/Wedian_dadas"
}

kalimantan_timur_urls = {
    "/wiki/Tenun_Ulap_Doyo",
    "/wiki/Belian_Bawo",
    "/wiki/Hudoq",
    "/wiki/Kwangkey",
    "/wiki/Lom_Plai",
    "/wiki/Mandau",
    "/wiki/Blontang",
    "/wiki/Erau",
    "/wiki/Sarung_Samarinda",
    "/wiki/Ganjur",
    "/wiki/Tari_Gong",
    "/wiki/Jatung_Utang"
}

kalimantan_utara_urls = {
    "/wiki/Bening_dayak",
    "/wiki/Jatung_Utang",
    "/wiki/Tari_Magunatip",
    "/wiki/Penurunan_Padaw_Tuju_Dulung",
    "/wiki/Bebelen",
    "/wiki/Melah_dan_Lakin_Ngayau",
    "/wiki/Inter_Kesuma",
    "/wiki/Bedibai"
}

sulawesi_selatan_urls = {
    "/wiki/Pinisi",
    "/wiki/Pa%27gellu",
    "/wiki/Sinriliq",
    "/wiki/Tari_Pakarena",
    "/wiki/Tongkonan",
    "/wiki/Badik",
    "/wiki/Ma%27badong",
    "/wiki/Coto_Makassar",
    "/wiki/Aqraga",
    "/wiki/Mappadendang",
    "/wiki/Tudang_Sipulung",
    "/wiki/Maudu_Lompoa",
    "/wiki/Lipa%27_Sabbe",
    "/wiki/Maccera_manurung",
    "/wiki/Tari_Salonreng",
    "/wiki/Barongko",
    "/wiki/Balla_To_Kajang",
    "/wiki/Kelong_Pakkiyo_Bunting",
    "/wiki/Passura%27",
    "/wiki/Rumah_Adat_Karampuang",
    "/wiki/Kapurung",
    "/wiki/Pajjaga_Bone_Balla",
    "/wiki/Kajangki",
    "/wiki/Gambus_Ogi",
    "/wiki/Songkabala_Accera_Kalompoang",
    "/wiki/Parade_Pasukan_A%27jaga_Tubarani",
    "/wiki/Sirawu%27_Sulo",
    "/wiki/Mattopang_Arajang",
    "/wiki/Rambu_Solo%27",
    "/wiki/Annyorong_lopi",
    "/wiki/Mangrara_Banua",
    "/wiki/Kelong_batti%27-batti%27",
    "/wiki/Maccera_arajang",
    "/wiki/Mappacci",
    "/wiki/Passureq",
    "/wiki/Mallangi_Arajang_Ri_Goarie",
    "/wiki/Macceratasi",
    "/wiki/Didek",
    "/wiki/Tari_Moriringgo"
}

sulawesi_utara_urls = {
    "/wiki/Tari_Maengket",
    "/wiki/Mane%27e",
    "/wiki/Kolintang",
    "/wiki/Tulude",
    "/wiki/Tari_kabela",
    "/wiki/Masamper",
    "/wiki/Tinutuan",
    "/wiki/Figura",
    "/wiki/Cakalang_fufu",
    "/wiki/Mapalus"
}

sulawesi_tenggara_urls = {
    "/wiki/Kalo_Sara",
    "/wiki/Kabanti",
    "/wiki/Lariangi",
    "/wiki/Kaghati",
    "/wiki/Mosehe",
    "/wiki/Tari_Malulo",
    "/wiki/Karia",
    "/wiki/Tari_Linda",
    "/wiki/Kantola",
    "/wiki/Istana_Malige",
    "/wiki/Kaago-Ago",
    "/wiki/Pakande-Kandea",
    "/wiki/Tari_Lumense",
    "/wiki/Tari_Mondotambe",
    "/wiki/Kabuenga"
}

sulawesi_tengah_urls = {
    "/wiki/Raigo",
    "/wiki/Sarung_Donggala",
    "/wiki/Malabot_tumpe",
    "/wiki/Padungku",
    "/wiki/Kaledo",
    "/wiki/Kakula",
    "/wiki/Modulu-Dulu",
    "/wiki/Balia",
    "/wiki/Tari_Torompio",
    "/wiki/Modero",
    "/wiki/Rumah_Tambi"
}

sulawesi_barat_urls = {
    "/wiki/Sayyang_pattudu",
    "/wiki/Passayang-sayang",
    "/wiki/Sandeq",
    "/wiki/Calong",
    "/wiki/Lipa_Saqbe_Mandar",
    "/wiki/Mappatammaq_Al-Quran",
    "/wiki/Maulidan_Salabose",
    "/wiki/Pupu",
    "/wiki/Kaliandaqdaq"
}

maluku_urls = {
    "/wiki/Ehe_Lawn",
    "/wiki/Tais_Pet",
    "/wiki/Tari_Maku-Maku",
    "/wiki/Rofaer_War_(Cuci_Parigi)",
    "/wiki/Poya",
    "/wiki/Pela",
    "/wiki/Sasi",
    "/wiki/Pukul_Manyapu",
    "/wiki/Sopi",
    "/wiki/Rumah_baileo",
    "/wiki/Dansa_Tali",
    "/wiki/Enbal",
    "/wiki/Tahuri",
    "/wiki/Pataheri/Matahena",
    "/wiki/Gula_Saparua",
    "/wiki/Tari_Lenso"
}

maluku_utara_urls = {
    "/wiki/Bambu_Gila",
    "/wiki/Soya-soya",
    "/wiki/Hibualamo",
    "/wiki/Tari_Legu_Sahu",
    "/wiki/Tarian_Tide-tide",
    "/wiki/Kukuhana",
    "/wiki/Sasadu",
    "/wiki/Yangere",
    "/wiki/Rion-rion",
    "/wiki/Laka_Baka",
    "/wiki/Bela_Yai",
    "/wiki/Tari_Togal",
    "/wiki/Tari_Lala",
    "/wiki/Bahasa_Bacan"
}

papua_urls = {
    "/wiki/Yosim_Pancar",
    "/wiki/Ukiran_Asmat",
    "/wiki/Noken",
    "/wiki/Tomako_Batu",
    "/wiki/Koteka",
    "/wiki/Tradisi_Wor",
    "/wiki/Elha",
    "/wiki/Aker",
    "/wiki/Rumah_Honai",
    "/wiki/Khombow",
    "/wiki/Terfo",
    "/wiki/Ndambu",
    "/wiki/Yu",
    "/wiki/Pokem",
    "/wiki/Aimaro_Hena_Taje",
    "/wiki/Bhukere",
    "/wiki/Sirew",
    "/wiki/Snap_Mor",
    "/wiki/Akonipuk",
    "/wiki/Helaehili",
    "/wiki/Karamo",
    "/wiki/Mbitoro",
    "/wiki/Patung_Karwar"
}

papua_barat_urls = {
    "/wiki/Papeda",
    "/wiki/Rumput_kebar",
    "/wiki/Fararior",
    "/wiki/Kuk_kir_kna",
    "/wiki/Mansorandak",
    "/wiki/Anu_Beta_Tubat",
    "/wiki/Orok"
}

province_food_urls = {
    "ACEH" : aceh_urls,
    "SUMATERA UTARA" : sumatera_utara_urls,
    "SUMATERA BARAT" : sumatera_barat_urls,
    "RIAU" : riau_place_urls,
    "KEPULAUAN RIAU" : kepulauan_riau_urls,
    "JAMBI" : jambi_urls,
    "SUMATERA SELATAN" : sumatera_selatan_urls,
    "LAMPUNG" : lampung_urls,
    "BENGKULU" : bengkulu_urls,
    "BANGKA BELITUNG" : bangka_belitung_urls,
    "GORONTALO" : gorontalo_urls,
    "DKI JAKARTA" : dki_jakarta_urls,
    "JAWA BARAT" : jawa_barat_urls,
    "BANTEN" : banten_urls,
    "JAWA TENGAH" : jawa_tengah_urls,
    "DI YOGYAKARTA" : yogyakarta_urls,
    "JAWA TIMUR" : jawa_timur_urls,
    "BALI" : bali_urls,
    "NUSA TENGGARA BARAT" : nusa_tenggara_barat_urls,
    "NUSA TENGGARA TIMUR" : nusa_tenggara_timur_urls,
    "KALIMANTAN BARAT" : kalimantan_barat_urls,
    "KALIMANTAN SELATAN" : kalimantan_selatan_urls,
    "KALIMANTAN TENGAH" : kalimantan_tengah_urls,
    "KALIMANTAN TIMUR" : kalimantan_timur_urls,
    "KALIMANTAN UTARA" : kalimantan_utara_urls,
    "SULAWESI SELATAN" : sulawesi_selatan_urls,
    "SULAWESI UTARA" : sulawesi_utara_urls,
    "SULAWESI TENGGARA" : sulawesi_tenggara_urls,
    "SULAWESI TENGAH" : sulawesi_tengah_urls,
    "SULAWESI BARAT" : sulawesi_barat_urls,
    "MALUKU" : maluku_urls,
    "MALUKU UTARA" : maluku_utara_urls,
    "PAPUA" : papua_urls,
    "PAPUA BARAT" : papua_barat_urls,
}
