aceh_urls = {
    "/wiki/Ayam_Tangkap",
    "/wiki/Bada_Reuteuk",
    "/wiki/Boh_Puniaram",
    "/wiki/Dalca",
    "/wiki/Kanji_Rumbi",
    "/wiki/Keukarah",
    "/wiki/Keumamah",
    "/wiki/Kuwah_eungk%C3%B4t_y%C3%A8e",
    "/wiki/Kuwah_it%C3%A9k",
    "/wiki/Kuwah_pliek_u",
    "/wiki/Kuwah_beulangong",
    "/wiki/Kolak",
    "/wiki/Martabak_Aceh",
    "/wiki/Masam_Keu%27eueng",
    "/wiki/Meuseukat",
    "/wiki/Mie_Aceh",
    "/wiki/Nasi_guri",
    "/wiki/Roti_canai",
    "/wiki/Roti_jala",
    "/wiki/Sambai_asam_udeueng",
    "/wiki/Sate_Matang",
    "/wiki/Sie_Reuboh",
    "/wiki/Timphan",
    "/wiki/Wajik",
    "/wiki/Lompong_Sagu",
    "/wiki/Masam_Jing",
    "/wiki/Pengat",
}

sumatera_utara_urls = {
"/wiki/Angsle",
    "/wiki/Arsik",
    "/wiki/Babi_Panggang_Karo",
    "/wiki/Bika_Ambon",
    "/wiki/Bolu_Gulung",
    "/wiki/Bubur_pedas",
    "/wiki/Bulung_Gadung",
    "/wiki/Cimpa",
    "/wiki/Cipera",
    "/wiki/Dalini_Horbo",
    "/wiki/Kuwah_eungk%C3%B4t_y%C3%A8e",
    "/wiki/Manisan_buah",
    "/wiki/Holat",
    "/wiki/Ikan_asap",
    "/wiki/Kwetiau",
    "/wiki/Lapis_Legit",
    "/wiki/Katimus",
    "/wiki/Lappet_Pohul-pohul",
    "/wiki/Lappet",
    "/wiki/Lemang",
    "/wiki/Mie_Gomak",
    "/wiki/Naniura",
    "/wiki/Ombus-Ombus",
    "/wiki/Pangsit",
    "/wiki/Pisang_Molen",
    "/wiki/Pok_pia",
    "/wiki/Roti_ketawa",
    "/wiki/Saksang",
    "/wiki/Sambal_Rias",
    "/wiki/Sambal_Andaliman",
    "/wiki/Sambal_Tuk_Tuk",
    "/wiki/Sambal_Gota",
    "/wiki/Sangsang",
    "/wiki/Soto_Medan",
    "/wiki/Tanggotanggo",
    "/wiki/Pagit-pagit",
    "/wiki/Tipa-tipa",
    "/wiki/Panggang_Geleng",
    "/wiki/Tuak",
}

sumatera_barat_urls = {
    "/wiki/Ale-ale",
    "/wiki/Asam_pedas",
    "/wiki/Ayam_pop",
    "/wiki/Beras_rendang",
    "/wiki/Bika",
    "/wiki/Bubur_kampiun",
    "/wiki/Cendol",
    "/wiki/Dadiah",
    "/wiki/Dendeng_balado",
    "/wiki/Dendeng_batokok",
    "/wiki/Gajebo",
    "/wiki/Galamai",
    "/wiki/Godok_Obuih",
    "/wiki/Gulai_banak",
    "/wiki/Pangek_cubadak",
    "/wiki/Gulai_itiak",
    "/wiki/Gulai_paku",
    "/wiki/Tambunsu",
    "/wiki/Gulai",
    "/wiki/Kalio",
    "/wiki/Keripik_sanjai",
    "/wiki/Karupuak_jangek",
    "/wiki/Karupuak_jariang",
    "/wiki/Ketan_durian",
    "/wiki/Katan_sarikayo",
    "/wiki/Kipang",
    "/wiki/Kipang_kacang",
    "/wiki/Lamang_tapai",
    "/wiki/Lapek_bugih",
    "/wiki/Lemang",
    "/wiki/Martabak_mesir",
    "/wiki/Nasi_kapau",
    "/wiki/Palai_bada",
    "/wiki/Pangek_masin",
    "/wiki/Perkedel",
    "/wiki/Pinyaram",
    "/wiki/Rendang",
    "/wiki/Samba_lado_tanak",
    "/wiki/Sate_Padang",
    "/wiki/Sate_Pariaman",
    "/wiki/Serabi",
    "/wiki/Soto_Padang",
    "/wiki/Wajik",
}

riau_place_urls = {
    "/wiki/Anyang",
    "/wiki/Bubur_lambok",
    "/wiki/Telur_dadar_tiram",
    "/wiki/Kemi",
    "/wiki/Kwetiau_Bagan",
    "/wiki/Mi_sagu",
    "/wiki/Sempolet",
}

kepulauan_riau_urls = {
    "/wiki/Asam_pedas",
    "/wiki/Cincalok",
    "/wiki/Kernas",
    "/wiki/Laksa",
    "/wiki/Lempeng",
    "/wiki/Mi_lendir",
    "/wiki/Mi_Tarempa",
    "/wiki/Mi_sagu",
    "/wiki/Nasi_dagang",
    "/wiki/Nasi_Lemak",
    "/wiki/Roti_canai",
    "/wiki/Roti_jala",
    "/wiki/Tabel_mando",
}

jambi_urls = {
    "/wiki/Brengkes_Tempoyak",
    "/wiki/Daging_masak_hitam",
    "/wiki/Gelamai_Perentak",
    "/wiki/Gulai_belut",
    "/wiki/Gulai_Ikan_Semah_(Khas_Merangin)",
    "/wiki/Gulai_Tekuyung",
    "/wiki/Gulai_tepek_ikan",
    "/wiki/Gulai_terjun_daging",
    "/wiki/Kerutup_ikan",
    "/wiki/Lemang",
    "/wiki/Nasi_gemuk",
    "/wiki/Nasi_lemak",
    "/wiki/Pempek_sambal",
    "/wiki/Rendang",
    "/wiki/Sambal_Salabance",
    "/wiki/Tempoyak",
    "/wiki/Bagar_hiu",
    "/wiki/Pakasam",
    "/wiki/Lema_(makanan)",
    "/wiki/Pendap",
    "/wiki/Tempoyak",
}

sumatera_selatan_urls = {
    "/wiki/Brengkes_Tempoyak",
    "/wiki/Bolu_Kojo",
    "/wiki/Burgo",
    "/wiki/Ikan_Salai",
    "/wiki/Kemplang",
    "/wiki/Kue_satu",
    "/wiki/Kue_maksuba",
    "/wiki/Laksa",
    "/wiki/Mie_Celor",
    "/wiki/Model",
    "/wiki/Nasi_Lemak",
    "/wiki/Nasi_Minyak",
    "/wiki/Otak-otak",
    "/wiki/Tekwan",
}

lampung_urls = {
    "/wiki/Gulai_Balak",
    "/wiki/Gulai_Taboh",
    "/wiki/Keripik_Pisang",
    "/wiki/Sekubal",
}

bengkulu_urls = {
    "/wiki/Kelicuk",
}

bangka_belitung_urls = {

}

gorontalo_urls = {
    "/wiki/Ayam_iloni",
    "/wiki/Binte_Biluhuta",
    "/wiki/Ikan_iloni",
    "/wiki/Sagela",
    "/wiki/Ilabulo",
    "/wiki/Pilitode",
    "/wiki/Bilentango",
    "/wiki/Sate_balanga",
    "/wiki/Sate_Gorontalo",
    "/wiki/Barlian",
    "/wiki/Pisang_goroho",
    "/wiki/Sukade",
}

dki_jakarta_urls = {
    "/wiki/Bir_Pletok",
    "/wiki/Emping",
    "/wiki/Es_selendang_mayang",
    "/wiki/Gado-gado",
    "/wiki/Geplak",
    "/wiki/Kerak_Telor",
    "/wiki/Ketoprak_(makanan)",
    "/wiki/Kroket",
    "/wiki/Kue_akar_kelapa",
    "/wiki/Kue_ape",
    "/wiki/Kue_Bakar",
    "/wiki/Kue_jongkong",
    "/wiki/Mi_kangkung",
    "/wiki/Nasi_kebuli",
    "/wiki/Nasi_Uduk",
    "/wiki/Onde-onde",
    "/wiki/Ongol-Ongol",
    "/wiki/Pelas",
    "/wiki/Risoles",
    "/wiki/Roti_Buaya",
    "/wiki/Sayur_Besan",
    "/wiki/Semur_Jengkol",
    "/wiki/Soto_Betawi",
    "/wiki/Soto_mie",
    "/wiki/Soto_Tangkar",
}

jawa_barat_urls = {
    "/wiki/Ambokueh",
    "/wiki/Bajigur",
    "/wiki/Bandrek",
    "/wiki/Batagor",
    "/wiki/Cireng",
    "/wiki/Colenak",
    "/wiki/Combro",
    "/wiki/Cuanki",
    "/wiki/Gehu_(makanan)",
    "/wiki/Gepuk",
    "/wiki/Karedok",
    "/wiki/Kolontong",
    "/wiki/Kue_Sus",
    "/wiki/Lotek",
    "/wiki/Mi_Kocok",
    "/wiki/Misro",
    "/wiki/Nasi_Timbel",
    "/wiki/Peuyeum",
    "/wiki/Pisang_Molen",
    "/wiki/Seblak",
    "/wiki/Serabi",
    "/wiki/Siomay",
    "/wiki/Soto_Bandung",
    "/wiki/Kue_Cubit",
    "/wiki/Tahu_bulat",
    "/wiki/Tahu_Sumedang",
    "/wiki/Tauco",
    "/wiki/Kupat_Tahu",
    "/wiki/Nasi_Tutug_Oncom",
    "/wiki/Tahu_Bulat",
    "/wiki/Kupat_Tahu",
    "/wiki/Pindang_Tetel",
    "/wiki/Hucap",
    "/wiki/Dodol_Garut",
    "/wiki/Dorokdok",
    "/wiki/Ladu",
    "/wiki/Docang",
    "/wiki/Empal_Gentong",
    "/wiki/Mi_koclok",
    "/wiki/Sega_Jamblang",
    "/wiki/Sega_Lengko",
    "/wiki/Tahu_Gejrot",
    "/wiki/Soto_Kuning",
    "/wiki/Doclang",
    "/wiki/Ayam_Goreng",
    "/wiki/Bubur_ayam",
    "/wiki/Mochi",
    "/wiki/Pepes",
    "/wiki/Colenak",
    "/wiki/Opak",
    "/wiki/Sate_Maranggi",
    "/wiki/Simping_(makanan)",
}

banten_urls = {
    "/wiki/Ayam_bekakak",
    "/wiki/Emping",
    "/wiki/Gemblong",
    "/wiki/Jojorong",
    "/wiki/Otak-otak",
    "/wiki/Rabeg",
    "/wiki/Semur",
}

jawa_tengah_urls = {
    "/wiki/Es_puter",
    "/wiki/Gandos",
    "/wiki/Gudangan",
    "/wiki/Lumpia_Semarang",
    "/wiki/Mi_kopyok",
    "/wiki/Nasi_Gandul",
    "/wiki/Roti_Ganjel_Rel",
    "/wiki/Soto_Semarang",
    "/wiki/Tahu_Gimbal",
    "/wiki/Kupat_tahu",
    "/wiki/Tahu_Bakso",
    "/wiki/Soto_Petanahan",
    "/wiki/Tongseng",
    "/wiki/Sate_Ambal",
    "/wiki/Ciwel",
    "/wiki/Lupis",
    "/wiki/Cenil",
    "/wiki/Jipang",
    "/wiki/Dawet_Ireng",
    "/wiki/Arem-arem",
    "/wiki/Kamir",
    "/wiki/Lontong_Dekem",
    "/wiki/Ogel-Ogel",
    "/wiki/Nasi_Grombyang",
    "/wiki/Nasi_Megono",
    "/wiki/Enting-enting",
    "/wiki/Getuk",
    "/wiki/Sumpil",
    "/wiki/Cotot",
    "/wiki/Kupat_Tahu",
    "/wiki/Wajik",
    "/wiki/Nagasari",
    "/wiki/Nasi_Jagung",
    "/wiki/Mendoan",
    "/wiki/Pecel_Gendar",
    "/wiki/Soto_Ayam",
    "/wiki/Tepo",
    "/wiki/Lengko",
    "/wiki/Olos",
    "/wiki/Pilus",
    "/wiki/Sate_Tegal",
    "/wiki/Tahu_Aci",
    "/wiki/Telur_Asin_Brebes",
    "/wiki/Sroto_Kriyik",
    "/wiki/Sroto_Bancar",
    "/wiki/Sate_Blater",
    "/wiki/Nopia",
    "/wiki/Getuk_goreng",
    "/wiki/Mino",
    "/wiki/Soto_Sokaraja",
    "/wiki/Tempe_mendoan",
    "/wiki/Bakmi_Nyemek",
    "/wiki/Cimplung",
    "/wiki/Getuk",
    "/wiki/Tegean",
    "/wiki/Lontong_sayur",
    "/wiki/Nasi_Megono",
    "/wiki/Soto_Pekalongan",
    "/wiki/Pindang_Tetel",
    "/wiki/Tauto",
    "/wiki/Adon-Adon_Coro",
    "/wiki/Carang_Madu",
    "/wiki/Rujak_Degan_Jepara",
    "/wiki/Es_Dawet",
    "/wiki/Es_Gempol",
    "/wiki/Horok-Horok",
    "/wiki/Kacang_Jepara",
    "/wiki/Kacang_Oven",
    "/wiki/Keciput",
    "/wiki/Kerupuk_Kerapu",
    "/wiki/Kue_bangkit",
    "/wiki/Nasi_tempong",
    "/wiki/Pecel_Ikan_Laut_Panggang",
    "/wiki/Pindang_Serani",
    "/wiki/Sate_Kikil",
    "/wiki/Sop_Udang",
    "/wiki/Soto_Jepara",
    "/wiki/Krecek",
    "/wiki/Cenil",
    "/wiki/Bandeng_presto",
    "/wiki/Nasi_gandul",
    "/wiki/Soto_kemiri",
    "/wiki/Petis_runting",
    "/wiki/Getuk",
    "/wiki/Lupis_(makanan)",
    "/wiki/Garang_Asem",
    "/wiki/Jenang_kudus",
    "/wiki/Lentog",
    "/wiki/Nasi_Grombyang",
    "/wiki/Nasi_megono",
    "/wiki/Nasi_pindang",
    "/wiki/Soto_Kudus",
    "/wiki/Pecel_Pakis",
    "/wiki/Clorot",
    "/wiki/Gula_Semut",
    "/wiki/Uli",
    "/wiki/Kaoya_dudul",
    "/wiki/Kerupuk_bakar",
    "/wiki/Lontong_Tuyuhan",
    "/wiki/Rawon",
    "/wiki/Asem-Asem_Daging",
    "/wiki/Botok_Telur_Asin",
    "/wiki/Nasi_Ndoreng",
    "/wiki/Wedang_Pekak",
    "/wiki/Momoh",
    "/wiki/Ampyang",
    "/wiki/Carang_Gesing",
    "/wiki/Dawet_Ayu",
    "/wiki/Dawet",
    "/wiki/Garang_Asem",
    "/wiki/Gudeg",
}

yogyakarta_urls = {
    "/wiki/Abangan",
    "/wiki/Alen-alen",
    "/wiki/Ampyang",
    "/wiki/Ayam_Geprek",
    "/wiki/Bakmi_Jawa",
    "/wiki/Bakpia",
    "/wiki/Bolu_emprit",
    "/wiki/Carang_Gesing",
    "/wiki/Cenil",
    "/wiki/Enting-enting",
    "/wiki/Gado-Gado",
    "/wiki/Gaplek",
    "/wiki/Gatot",
    "/wiki/Geplak",
    "/wiki/Getuk",
    "/wiki/Growol",
    "/wiki/Gudangan",
    "/wiki/Gudeg",
    "/wiki/Gudeg_Manggar",
    "/wiki/Jadah_Manten",
    "/wiki/Juwawut",
    "/wiki/Kipo",
    "/wiki/Klepon",
    "/wiki/Mendut",
    "/wiki/Nasi_Kucing",
    "/wiki/Nasi_Pecel",
    "/wiki/Onde-onde",
    "/wiki/Ongol-ongol",
    "/wiki/Opor_Ayam",
    "/wiki/Pecel",
    "/wiki/Rengginang",
    "/wiki/Sate_Klathak",
    "/wiki/Selat",
    "/wiki/Semar_Mesem",
    "/wiki/Timus",
    "/wiki/Tiwul",
    "/wiki/Tongseng",
    "/wiki/Trancam",
    "/wiki/Tumpeng",
    "/wiki/Urap",
    "/wiki/Wajik",
    "/wiki/Ronde_(makanan)",
    "/wiki/Wedang_Secang",
    "/wiki/Wedang_Uwuh",
    "/wiki/Yangko",
}

jawa_timur_urls = {
    "/wiki/Rawon",
    "/wiki/Lontong_Balap",
    "/wiki/Bebek_goreng",
    "/wiki/Krengsengan",
    "/wiki/Rujak_Cingur",
    "/wiki/Semanggi_(makanan)",
    "/wiki/Tahu_Tek",
    "/wiki/Kue_cucur",
    "/wiki/Lontong_Kupang",
    "/wiki/Sate_kerang",
    "/wiki/Kerupuk_udang",
    "/wiki/Bandeng_asap",
    "/wiki/Bandeng_presto",
    "/wiki/Petis",
    "/wiki/Lontong_balap",
    "/wiki/Kupang_Lontong",
    "/wiki/Weci",
    "/wiki/Menjes",
    "/wiki/Onde-onde",
    "/wiki/Nasi_Pecel",
    "/wiki/Soto_Lamongan",
    "/wiki/Tahu_campur",
    "/wiki/Tahu_Tek",
    "/wiki/Wingko_Babat",
    "/wiki/Tiwul",
    "/wiki/Soto_Kediri",
    "/wiki/Tahu_Kuning",
    "/wiki/Gethuk_Pisang",
    "/wiki/Sate_Bekicot",
    "/wiki/Rujak_Soto",
    "/wiki/Bothok",
    "/wiki/Lemper",
    "/wiki/Bungkuk",
    "/wiki/Lemet",
    "/wiki/Lanun",
    "/wiki/Lupis",
    "/wiki/Jemblem",
    "/wiki/Pukis",
    "/wiki/Rujak_Petis",
    "/wiki/Rujak_Manis",
    "/wiki/Pare",
    "/wiki/Pecel_Madiun",
    "/wiki/Brem",
    "/wiki/Lempeng",
    "/wiki/Gado_Gado",
    "/wiki/Rawon",
    "/wiki/Lepet_Jagung",
    "/wiki/Bakso_Malang",
    "/wiki/Keripik_Kentang",
    "/wiki/Keripik_Singkong",
    "/wiki/Keripik_Tempe",
    "/wiki/Angsle",
    "/wiki/Rujak_Cingur",
    "/wiki/Tahu_Tek",
    "/wiki/Ronde",
    "/wiki/Mendol",
    "/wiki/Nasi_Krawu",
    "/wiki/Tempe_Penyet",
    "/wiki/Sego_Tempong",
    "/wiki/Nasi_Boranan",
    "/wiki/Nasi_Becek",
    "/wiki/Keripik_Tempe",
    "/wiki/Tape",
    "/wiki/Suwar-suwir",
    "/wiki/Gulai",
    "/wiki/Gangsa",
    "/wiki/Klepon",
    "/wiki/Sate",
    "/wiki/Sate_lalat",
    "/wiki/Lepet",
    "/wiki/Soto_Madura",
    "/wiki/Nasi_Jagung",
    "/wiki/Pelas",
    "/wiki/Ampo",
    "/wiki/Keripik_Pisang",
    "/wiki/Sale_Pisang",
    "/wiki/Bajingan",
    "/wiki/Kolong_Klitik",
}

bali_urls = {
    "/wiki/Ayam_Betutu",
    "/wiki/Babi_Guling",
    "/wiki/Bandot",
    "/wiki/Be_Pasih_Mesambel_Matah",
    "/wiki/Garang_asem",
    "/wiki/Srombotan",
    "/wiki/Urap",
    "/wiki/Lawar",
    "/wiki/Sate_Lilit",
    "/wiki/Sate_Penyu",
    "/wiki/Srombotan",
    "/wiki/Timbungan",
    "/wiki/Nasi_Jenggo",
    "/wiki/Urutan_(Masakan_Bali)",
    "/wiki/Bubur_sumsum",
    "/wiki/Jaja_Begina",
    "/wiki/Jaja_Bendu",
    "/wiki/Jaja_Klepon",
    "/wiki/Jaja_Wajik",
    "/wiki/Rujak_Kuah_Pindang",
    "/wiki/Rujak_Manis",
}

nusa_tenggara_barat_urls = {
    "/wiki/Salome",
    "/wiki/Bingka_dolu",
    "/wiki/Barongko",
    "/wiki/Ayam_Taliwang",
    "/wiki/Sate_Bulayak",
    "/wiki/Plecing_Kangkung",
    "/wiki/Beberuk_terong",
    "/wiki/Ares",
    "/wiki/Singang",
    "/wiki/Ayam_Rarang",
    "/wiki/Sate_Bulayak",
    "/wiki/Sako",
    "/wiki/Lada",
}

nusa_tenggara_timur_urls = {
    "/wiki/Jagung_bose",
    "/wiki/Jagung_titi",
    "/wiki/Katemak",
    "/wiki/Kolo",
    "/wiki/Lori",
    "/wiki/Nasi_kacang_merah",
    "/wiki/Rumpu_rampe",
    "/wiki/Se%27i",
    "/wiki/Ubi_nuabosi",
}

kalimantan_barat_urls = {
    "/wiki/Kerupuk_Basah",
    "/wiki/Lemang",
    "/wiki/Lidah_Buaya",
    "/wiki/Tempoyak",
    "/wiki/Bingka",
    "/wiki/Bubur_gunting",
    "/wiki/Kue_pasung",
    "/wiki/Lempok",
}

kalimantan_selatan_urls = {
}

kalimantan_tengah_urls = {
    "/wiki/Dami",
    "/wiki/Kalumpe",
    "/wiki/Lemang",
    "/wiki/Paing",
    "/wiki/Wadi",
}

kalimantan_timur_urls = {
}

kalimantan_utara_urls = {
    "/wiki/Lawa",
    "/wiki/Kepiting_soka",
    "/wiki/Naul",
}

sulawesi_selatan_urls = {
    "/wiki/Apam_paranggi",
    "/wiki/Baje%27",
    "/wiki/Barongko",
    "/wiki/Bassang",
    "/wiki/Bipang",
    "/wiki/Bingka_barandam",
    "/wiki/Nagasari",
    "/wiki/Jalangkote",
    "/wiki/Katerisallang",
    "/wiki/Kue_Putu",
    "/wiki/Ongol-ongol",
    "/wiki/Pallu_Butung",
    "/wiki/Pisang_peppe",
    "/wiki/Pisang_Ijo",
    "/wiki/Bakpao",
    "/wiki/Gemblong",
    "/wiki/Gogos",
    "/wiki/Buras",
    "/wiki/Coto_Makassar",
    "/wiki/Dangke",
    "/wiki/Ikan_rica",
    "/wiki/Kapurung",
    "/wiki/Lawa",
    "/wiki/Pallu_Butung",
    "/wiki/Pacco%27",
    "/wiki/Sop_Kikil",
    "/wiki/Sop_Konro",
    "/wiki/Sop_Saudara",
    "/wiki/Kawah",
}

sulawesi_utara_urls = {
    "/wiki/Bagea",
    "/wiki/Binyolos",
    "/wiki/Bobengka",
    "/wiki/Klappertaart",
    "/wiki/Koyabu",
    "/wiki/Lampu_lampu",
    "/wiki/Panada",
    "/wiki/Wajik",
    "/wiki/Ayam_Rica-Rica",
    "/wiki/Mi_cakalang",
    "/wiki/Roa",
    "/wiki/RW",
    "/wiki/Tinutuan",
    "/wiki/Tinorangsak",
}

sulawesi_tenggara_urls = {
     "/wiki/Kabuto",
    "/wiki/Lapa-lapa",
    "/wiki/Susuru",
    "/wiki/Sinonggi",
    "/wiki/Tolaki",
    "/wiki/Soami",
}

sulawesi_tengah_urls = {
    "/wiki/Apam_paranggi",
    "/wiki/Mandura",
    "/wiki/Serabi",
    "/wiki/Kaledo",
    "/wiki/Palumara",
    "/wiki/Inuyu",
    "/wiki/Kapurung",
    "/wiki/Onyop",
    "/wiki/Tombouat",
}

sulawesi_barat_urls = {
    "/wiki/Kue_Paso",
    "/wiki/Apam",
    "/wiki/Pukis",
    "/wiki/Apam_paranggi",
    "/wiki/Jepa",
    "/wiki/Bau_peapi",
    "/wiki/Loka_anjoroi",
}

maluku_urls = {
    "/wiki/Colo-colo",
    "/wiki/Papeda",
    "/wiki/Nasi_Lapola",
    "/wiki/Sambal_Pepaya",
    "/wiki/Ikan_asap",
    "/wiki/Bagea",
    "/wiki/Kasbi",
    "/wiki/Lat",
    "/wiki/Bubur_sagu_Ambon",
    "/wiki/Bubur_Ne",
    "/wiki/Gogos",
    "/wiki/Kue_asida",
}

maluku_utara_urls = {
    "/wiki/Gatang_kenari",
    "/wiki/Gohu_ikan",
    "/wiki/Kasbi",
    "/wiki/Kohu-kohu",
    "/wiki/Ula-ula",
    "/wiki/Anuve_Habre",
    "/wiki/Aunu_Senebre",
    "/wiki/Eurimoo",
    "/wiki/Sate_ulat_sagu",
    "/wiki/Nasi_Goreng_Jawa",
    "/wiki/Nasi_Langgi",
    "/wiki/Nasi_Kuning",
    "/wiki/Panada",
    "/wiki/Pukis",
    "/wiki/Bika_Ambon",
}

papua_urls = {
    "https://id.wikipedia.org/wiki/Sate_ulat_sagu",
    "https://id.wikipedia.org/wiki/Aunu_Senebre",
    "https://id.wikipedia.org/wiki/Eurimoo",
    "https://id.wikipedia.org/wiki/Anuve_Habre",
}

papua_barat_urls = {
}

province_food_urls = {
    "ACEH" : aceh_urls,
    "SUMATERA UTARA" : sumatera_utara_urls,
    "SUMATERA BARAT" : sumatera_barat_urls,
    "RIAU" : riau_place_urls,
    "KEPULAUAN RIAU" : kepulauan_riau_urls,
    "JAMBI" : jambi_urls,
    "SUMATERA SELATAN" : sumatera_selatan_urls,
    "LAMPUNG" : lampung_urls,
    "BENGKULU" : bengkulu_urls,
    "BANGKA BELITUNG" : bangka_belitung_urls,
    "GORONTALO" : gorontalo_urls,
    "DKI JAKARTA" : dki_jakarta_urls,
    "JAWA BARAT" : jawa_barat_urls,
    "BANTEN" : banten_urls,
    "JAWA TENGAH" : jawa_tengah_urls,
    "DI YOGYAKARTA" : yogyakarta_urls,
    "JAWA TIMUR" : jawa_timur_urls,
    "BALI" : bali_urls,
    "NUSA TENGGARA BARAT" : nusa_tenggara_barat_urls,
    "NUSA TENGGARA TIMUR" : nusa_tenggara_timur_urls,
    "KALIMANTAN BARAT" : kalimantan_barat_urls,
    "KALIMANTAN SELATAN" : kalimantan_selatan_urls,
    "KALIMANTAN TENGAH" : kalimantan_tengah_urls,
    "KALIMANTAN TIMUR" : kalimantan_timur_urls,
    "KALIMANTAN UTARA" : kalimantan_utara_urls,
    "SULAWESI SELATAN" : sulawesi_selatan_urls,
    "SULAWESI UTARA" : sulawesi_utara_urls,
    "SULAWESI TENGGARA" : sulawesi_tenggara_urls,
    "SULAWESI TENGAH" : sulawesi_tengah_urls,
    "SULAWESI BARAT" : sulawesi_barat_urls,
    "MALUKU" : maluku_urls,
    "MALUKU UTARA" : maluku_utara_urls,
    "PAPUA" : papua_urls,
    "PAPUA BARAT" : papua_barat_urls,
}
